### ISSUE TITLE
BOM Submission

### ISSUE THREAD

**Issue by timChase98** [mbourgeois2/ECE-388-Digital-Level-Design-Project#2]
- [x] submissions must be in CSV
- [x] price breakdowns should be for unit price at quantity 

This otherwise looks ok.  fix these things ASAP and you should be good

**Comment by mbourgeois2** [comment]
Hello Tim,

I'm a little confused, do you mean the BOM should be a CSV file? If so, I believe mine already is. For the second issue my prices are the unit price (price of 1 when buying 100 for example), do you mean for the whole amount (price of 100 when buying 100)? Also some of the parts I can only find in quantities of 200 or 500, do you want me to change the column name?

Thanks,
Michael Bourgeois

________________________________

**Comment by timChase98** [comment]
You are correct about the CSV.  I think I typed that into the window.  For the unit price it should be the cost per unit as the specified price.  If the minimum quantity for a part is 20, the price 1 and price 10 columns should be blank, and the first column with data in it would be the price 100 column with the price/part @ quantity 100.

**Comment by mbourgeois2** [comment]
I can't find those parts in quantities of 100, they go right from 20 to 200. One of my parts is the same way, but for 50 and 500 instead. Should I put the price/part for 200/500 in the 100 column, or should I put 20/50 in the 100 column?

________________________________

**Comment by timChase98** [comment]
If the price/part is the same for parts in quantities from 20 to 200, and 100 is in the interval from 20 to 200.  The price/part for 100 uses the price/part for the range from 20 to 200.

**Comment by mbourgeois2** [comment]
Ok thanks for clarifying, I fixed the prices now, sorry about that.

Thanks,
Michael Bourgeois

________________________________

**Comment by timChase98** [comment]
Ok Push you changes, fill out the check list and close this issue.  I'll look it over and check you off or open a new issue if you still nee to make changes

**Comment by timChase98** [comment]
You have been marked as good to order parts
