### ISSUE TITLE
Schematic Submission

### ISSUE THREAD

**Issue by timChase98** [mbourgeois2/ECE-388-Digital-Level-Design-Project#3]
- [x] Render of schematic is rotated 90 degrees 
- [x] Schematics should have clear flow from left-right 
  - [x] Power input top left
  - [x] Inputs to uController middle left 
  - [x] uController in the center
  - [x] uController outputs to right  
- [x] Power flags should label the voltage they carry. ie +5V -12V 3.3V 
  - [x] Supply flags should always point up
  - [x] GND flags should always point down
  - [x] The battery should be upright
- [x] Your reverse voltage protection would cause a significant voltage drop over the diode.  Take a look at [THIS](https://www.ti.com/lit/an/slva139/slva139.pdf?ts=1602775249932&ref_url=https%253A%252F%252Fwww.google.com%252F) app note from TI
- [x] nonpolarized components should use nonpolarized symbols
  - [x] If C6 is intended to be polarized it's reverse biased 
- [x] Why are there resistors on the programming lines? 
- [x] Nets should have more meaningful names than PB0

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by mbourgeois2** [comment]
One question, what is the output voltage of the isp programmers? I'm asking because my accelerometer's max voltage is 3.46V and if the programmers output 5V that could be an issue

**Comment by timChase98** [comment]
The ISP does not output a voltage

**Comment by mbourgeois2** [comment]
ok thank you

**Comment by timChase98** [comment]
-[ ] What is the purpose of U3? 
-[ ] Clean up the power nets on the top of the MPU-6050

**Comment by mbourgeois2** [comment]
U3 is a decoder, I implemented it to try and simplify the wiring on the ports, should I take it back out?

**Comment by mbourgeois2** [comment]
@timChase98 hey tim, i'm sorry if you're busy but everyone i've talked to so far has had their schems looked at again, if you haven't gotten to mine yet that's all good, i was just wondering

**Comment by timChase98** [comment]
- [x] Add a pullup resistor to the reset line of the uController 
- [x] Clean up your power nets so everything is pointing in the right direction.  
- [x] VCC on the ISP should connect to the VCC pin of the uController.  You have it connected to the battery 

Sorry I had this type out but apparently I never hit send, fix these things and I'll give it a pass

**Comment by mbourgeois2** [comment]
@timChase98 Ok I think these are fixed now

**Comment by mbourgeois2** [comment]
@timChase98 I don't think you reopened the issue, just letting you know I fixed it, can you please review my changes when you can

**Comment by timChase98** [comment]
I'll accept this.  You can move onto payout.  To get a pass all labels should sit on top of the nets they are connected to not next to them.  You did this correct for the net labels on the left side of the uController, fix them everywhere else

**Comment by mbourgeois2** [comment]
@timChase98 ok i think i fixed the labels

**Comment by mbourgeois2** [comment]
@timChase98 did i pass

**Comment by timChase98** [comment]
Looks good. Move onto layout
