### ISSUE TITLE
Board Submission

### ISSUE THREAD

**Issue by mbourgeois2** [mbourgeois2/ECE-388-Digital-Level-Design-Project#4]
hey tim, I submitted my board, can you look at it when you have time?

**Comment by timChase98** [comment]
This actually looks pretty good.  You need to increase the font size for your text, You also need to increase the trace width on your power traces to 12 mil.  Minimum to get manufactured is 6mil or .16mm.  This could fit on a smaller board but if you change the trace width and font size I'll accept this.

**Comment by mbourgeois2** [comment]
Thanks for the feedback tim, i made my font bigger, but i thought my power trace width was already 12mil, and the rest of the traces are 8mil

![12mil](https://user-images.githubusercontent.com/60248055/98905279-241e0a00-2489-11eb-821a-29cad90f51a0.PNG)

![8mil](https://user-images.githubusercontent.com/60248055/98905283-25e7cd80-2489-11eb-9c9c-558df1ad3eae.PNG)

**Comment by mbourgeois2** [comment]
in addition to this, setting my power trace width any high than 13 results in a clearance error on the mpu-6050, this is demonstrated with the trace width set to 16mil:

![16mil](https://user-images.githubusercontent.com/60248055/98906796-bde6b680-248b-11eb-946c-34f26f694878.PNG)

**Comment by mbourgeois2** [comment]
one other thing, would the size of the lenny face next to the battery cause any manufacturing issues? i'd like it to be there but if it comes down to it i don't want sacrifice the manufacturability of my board for a stupid meme

**Comment by timChase98** [comment]
Your copper layers look fine. If you wanted to redo your layout after the deadline for more points I would recommend adding a GND plane on the bottom layer.  you still need to increase the stroke size of all of your designators to 6mil or larger.  This also applies to the lenny face.  I believe there is a ULP to do this for you.  Fix the font size and I'll accept this, add the gnd plane and i'll pass it.

**Comment by mbourgeois2** [comment]
i did add a ground plane

**Comment by mbourgeois2** [comment]
at least i think i do? i made a polygon covering the board, then called it GND, my airwires went away after that

**Comment by timChase98** [comment]
Did you update the gerbers on github? The ones I'm looking at doesn't have a plane 
![image](https://user-images.githubusercontent.com/30877609/98963889-28244900-24d6-11eb-8416-8fad139b4aa1.png)

**Comment by mbourgeois2** [comment]
ok i pushed it again, here is a screencap of my board
![image](https://user-images.githubusercontent.com/60248055/98964705-214a0600-24d7-11eb-8a3d-f0fb89d8e0df.png)
for some reason it only shows up if i run ratsnest

**Comment by timChase98** [comment]
You have to run ratsnest for it to actually fill the plane. It also looks like you are using the wrong cam processor.  Use the 388Cam file

**Comment by mbourgeois2** [comment]
ok i downloaded a new cam file from the repo and pushed my changes, also adjusted my text

**Comment by mbourgeois2** [comment]
also is the correct ULP normalize-text? that's the one i used, also a quick google search indicated that stroke size was the ratio times the size of the text is this correct

**Comment by timChase98** [comment]
The stroke size is the width of a line.  Normalize-text is the correct ULP

**Comment by mbourgeois2** [comment]
im trying to generate the gerbers myself and cannot see the ground plane and am not sure why, any ideas?

**Comment by mbourgeois2** [comment]
i'm using the ece388 cam file

**Comment by timChase98** [comment]
This looks correct now.  I'll pass this

**Comment by mbourgeois2** [comment]
you were able to see the ground plane?

**Comment by timChase98** [comment]
Yes its there now.  You are good

**Comment by timChase98** [comment]
Your board was sent to fab

**Comment by mbourgeois2** [comment]
@timChase98 hey tim, so i was doing some more prototyping when i realized that i forgot to ground pins 4&5 on my decoder (seen below) 
![g2ag2b](https://user-images.githubusercontent.com/60248055/99440030-fe0ec480-28e3-11eb-9163-be2105612c32.PNG)
![wrongpins](https://user-images.githubusercontent.com/60248055/99440043-00711e80-28e4-11eb-8d4f-a7218c0cb4a2.PNG)

the decoder was a last minute addition and i should have seen this coming if i did more prototyping with it earlier
this means my board will not work straight away, however i was wondering if it would be possible to solder in some rework wires, like this
https://nexlogic.com/wp-content/uploads/2015/10/PCB-Rework2.png
this would make my board (maybe?) function as intended

**Comment by timChase98** [comment]
Yes mod wiring is something that you end up doing a lot of in this type of prototyping.  We have all the necessary equipments 211, available any time I'm on campus.
